name: Test
on:
  push:
    branches:
      - main

jobs:
  unittest:
    name: Test
    runs-on: ubuntu-22.04
    steps:

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: Install plugin
        run: |
          trivy plugin install github.com/dramf/md
          trivy plugin info md

      - name: Run plugin
        run: |
          trivy image tomcat -f json --output plugin=md
          cat trivy-report.md >> $GITHUB_STEP_SUMMARY