name: Test
on:
  push:
    branches:
      - main

jobs:
  unittest:
    name: Test
    runs-on: ubuntu-22.04
    steps:

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: Install plugin
        run: |
          trivy plugin install github.com/dramf/md
          trivy plugin info md

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
          output: 'plugin=md'
          skip-setup-trivy: true

#      - name: Run plugin
#        run: |
#            trivy image tomcat:9.0.54 -f json --output plugin=md

      - name: Get report summary
        run: cat trivy-report.md >> $GITHUB_STEP_SUMMARY