name: Trivy scan
on:
  push:
    branches:
      - main

jobs:
  unittest:
    name: Trivy scan
    runs-on: ubuntu-22.04
    steps:

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: Install plugin
        run: |
          trivy plugin install github.com/dramf/md

      - name: Run plugin
        run: |
            trivy image alpine -f json --output plugin=md

      - name: Get Summary
        run: cat trivy-report.md >> $GITHUB_STEP_SUMMARY